name: sklearn-xarray
channels:
  - conda-forge
dependencies:
  - python=3.7
  - numpy
  - scipy
  - scikit-learn
  - pandas
  - xarray
  - pytest
  - matplotlib
  - sphinx==2.4.4
  - sphinx-gallery
  - sphinx_rtd_theme
  - numpydoc
  # install sklearn-xarray in development mode through pip
  - pip:
    - -e .
